#!/usr/bin/env python3
"""Import the six original FR/EN movement descriptions and unchanged local media."""
from pathlib import Path
import json,re,shutil,hashlib
root=Path(__file__).resolve().parents[1];live=root.parent/'useprocess'
source=live/'WelcomePlan/FaceMorningRoutineCatalog.swift';text=source.read_text()
cases=['sautsSurPlace','rebondsPointes','brasAuCiel','brasEnCroix','ouvertureThorax','monteesGenoux']
assets=['routinesauts','routinepointes','routinebrasciel','routinebrascroix','routinethorax','routinegenoux']
resources=['lymph_01','lymph_02','lymph_03','lymph_05','lymph_06','lymph_07']
ids=['daily-routine-sauts','daily-routine-pointes','daily-routine-bras','daily-routine-brascroix','daily-routine-thorax','daily-routine-genoux']
blocks={name:text.split('var '+name+':',1)[1].split(next_name,1)[0]for name,next_name in [('shortTitle','var coachingCue'),('howToSteps','var benefits'),('benefits','static func from')]}
pair=re.compile(r'AppCopy\.t\(\s*("(?:[^"\\]|\\.)*")\s*,\s*en:\s*("(?:[^"\\]|\\.)*")\s*\)',re.S)
def items(block,case):
 section=block.split('case .'+case+':',1)[1].split('case .',1)[0]
 return [(json.loads(a),json.loads(b))for a,b in pair.findall(section)]
def quoted(s):return json.dumps(s,ensure_ascii=False).replace('$','\\$')
def pairs(values):return 'listOf('+','.join(quoted(fr)+' to '+quoted(en)for fr,en in values)+')'
rows=[];hashes={str(source):hashlib.sha256(source.read_bytes()).hexdigest()}
for index,case in enumerate(cases):
 title=items(blocks['shortTitle'],case);instructions=items(blocks['howToSteps'],case);benefits=items(blocks['benefits'],case)
 assert len(title)==1 and len(instructions)==3 and len(benefits)==4
 duration=int(re.search(r'case \.'+case+r': return (\d+)',text).group(1))
 rows.append('        RoutineStep('+','.join([quoted(ids[index]),str(index+1),str(duration),quoted(resources[index]),quoted(assets[index]),quoted(title[0][0])+' to '+quoted(title[0][1]),pairs(instructions),pairs(benefits)])+')')
 for original,destination in [(live/'Resources/LymphCircuit'/f'{resources[index]}.mp4',root/'app/src/main/res/raw'/f'{resources[index]}.mp4'),(live/'Assets.xcassets/Training/Routines'/f'{assets[index]}.imageset'/f'{assets[index]}.png',root/'app/src/main/res/drawable-nodpi'/f'{assets[index]}.png')]:
  data=original.read_bytes()
  if destination.suffix=='.png' and data.startswith(b'\xff\xd8'):
   stale=destination;destination=destination.with_suffix('.jpg')
   if stale.exists():stale.unlink()  # Only this importer's generated resource.
  shutil.copy2(original,destination);hashes[str(original)]=hashlib.sha256(original.read_bytes()).hexdigest();assert original.read_bytes()==destination.read_bytes()
output='''package com.process.android

/** Original Process routine copy/data. Generated by scripts/import-routine.py; no health claims added. */
data class RoutineStep(val id:String,val number:Int,val durationSeconds:Int,val videoResource:String,val imageResource:String,val title:Pair<String,String>,val instructions:List<Pair<String,String>>,val benefits:List<Pair<String,String>>) {
    fun title(english:Boolean)=if(english)title.second else title.first
    val durationLabel:String get()=if(durationSeconds%60==0)"${durationSeconds/60} min"else if(durationSeconds>=60)"${durationSeconds/60}:${(durationSeconds%60).toString().padStart(2,'0')}"else"$durationSeconds s"
}
object ProcessRoutineCatalog {
    val steps=listOf(
'''+',\n'.join(rows)+'''
    )
    val fullSessionSeconds:Int get()=steps.sumOf {it.durationSeconds}
}
'''
(root/'app/src/main/java/com/process/android/ProcessRoutineCatalog.kt').write_text(output)
(root/'parity/routine-source.json').write_text(json.dumps({'sourceSha256':hashes,'entries':6,'totalSeconds':280,'mediaCopiedByteForByte':True},indent=2)+'\n')
print('Imported six original bilingual routines, six unchanged videos and six unchanged images.')
