#!/usr/bin/env bash
# Affiche les valeurs Process pour Apple Retention Messaging + RevenueCat dashboard.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

echo "=== Process — Apple Retention Messaging checklist ==="
echo ""
echo "Formulaire Apple (Account Holder)"
echo "  App Name   : Process : Debloat ton visage"
echo "  Apple ID   : 6753808143"
echo "  Bundle ID  : com.useprocess"
echo "  Endpoint   : (copier depuis RevenueCat → Apps → iOS → Retention Messaging Endpoint)"
echo ""
echo "RevenueCat dashboard"
echo "  Lifecycle → Retention → Apple Retention Messaging API"
echo "  Entitlement: premium"
echo "  ASC group  : 21837790"
echo ""
echo "Product IDs (sélectionner tous les abos, pas lifetime):"
echo "  com.useprocess.weekly899"
echo "  com.useprocess.annual3499"
echo "  com.useprocess.monthly999"
echo "  com.useprocess.annual4999"
echo "  com.useprocess.monthly"
echo "  com.useprocess.annual"
echo ""
echo "Default message — fr-FR"
echo "  Title    : Garde ton plan debloat actif"
echo "  Subtitle : Scans visage, routine et coach restent débloqués tant que tu restes abonné."
echo ""
echo "Default message — en-US"
echo "  Title    : Keep your debloat plan going"
echo "  Subtitle : Face scans, routine, and coach stay unlocked while you stay subscribed."
echo ""
echo "Trial message — eligibility: Is in free trial"
echo "  fr-FR title    : Ton essai t'aide déjà à debloat"
echo "  fr-FR subtitle : Continue maintenant pour garder tes scans, ta routine et ton coach."
echo "  en-US title    : Your trial is already helping you debloat"
echo "  en-US subtitle : Continue now to keep your scans, routine, and coach."
echo ""
echo "App (déjà implémenté)"
echo "  Paramètres → Mon compte → Gérer mon abonnement"
echo ""
echo "Docs: $ROOT/firebase/RETENTION_MESSAGING.md"
echo "      https://www.revenuecat.com/docs/platform-resources/apple-platform-resources/apple-retention-messaging-api"
