package com.process.android

// Generated from Process DebloatFoodCatalog.swift; do not edit data manually.
object DebloatFoods {
 val all:List<DebloatFood> = listOf(
  DebloatFood("concombre","Concombre",FoodCategory.legumes,FoodTier.hero,147.0,2.0,13.0,"N°1 anti-gonflement : eau + K, quasi zéro sodium.",listOf("soir-safe","high-K","drainant"),listOf(),"1/2 à 1 concombre"),
  DebloatFood("courgette","Courgette",FoodCategory.legumes,FoodTier.hero,261.0,8.0,18.0,"Légume drainant, parfait le soir pour un visage plus net.",listOf("soir-safe","high-K"),listOf(),"200 g cuite"),
  DebloatFood("asperge","Asperge",FoodCategory.legumes,FoodTier.prefer,202.0,2.0,14.0,"Diurétique naturel, aide à évacuer l’eau en excès.",listOf("soir-safe","drainant"),listOf(),"1 botte"),
  DebloatFood("celeri","Céleri branche",FoodCategory.legumes,FoodTier.prefer,260.0,80.0,11.0,"Croquant drainant — garde le sodium bas en le mangeant nature.",listOf("soir-safe","drainant"),listOf(),"2–3 branches"),
  DebloatFood("fenouil","Fenouil",FoodCategory.legumes,FoodTier.prefer,414.0,52.0,17.0,"Riche en K, digeste, excellent pour limiter la rétention.",listOf("soir-safe","high-K"),listOf(),"1 bulbe"),
  DebloatFood("artichaut","Artichaut",FoodCategory.legumes,FoodTier.prefer,370.0,94.0,60.0,"Soutient le drainage et apporte du magnésium utile.",listOf("soir-safe"),listOf(),"1 artichaut"),
  DebloatFood("poireau","Poireau",FoodCategory.legumes,FoodTier.prefer,180.0,20.0,28.0,"Base soupe anti-rétention, faible en sodium si non salée.",listOf("soir-safe"),listOf(),"1 poireau"),
  DebloatFood("epinards","Épinards",FoodCategory.legumes,FoodTier.hero,558.0,79.0,79.0,"Triple levier : potassium + magnésium + volume drainant.",listOf("soir-safe","high-K"),listOf(),"150 g cuits"),
  DebloatFood("blettes","Blettes",FoodCategory.legumes,FoodTier.prefer,379.0,213.0,81.0,"Feuilles riches en K/Mg — rincer et cuire sans sel.",listOf("high-K"),listOf(),"200 g"),
  DebloatFood("tomate","Tomate",FoodCategory.legumes,FoodTier.prefer,237.0,5.0,11.0,"Fraîche ou concentrée nature : boost K sans sel ajouté.",listOf("soir-safe","high-K"),listOf("tomate-concentree"),"2 tomates"),
  DebloatFood("tomate-concentree","Tomate concentrée nature",FoodCategory.potassium,FoodTier.hero,1014.0,58.0,68.0,"Concentrateur de potassium — choisir sans sel ajouté.",listOf("high-K","soir-safe"),listOf(),"2 c. à s."),
  DebloatFood("poivron","Poivron",FoodCategory.legumes,FoodTier.prefer,211.0,4.0,12.0,"Couleur, croquant, sodium quasi nul.",listOf("soir-safe"),listOf(),"1 poivron"),
  DebloatFood("radis-noir","Radis noir",FoodCategory.legumes,FoodTier.prefer,233.0,39.0,25.0,"Drainant classique, utile en cure courte visage.",listOf("drainant"),listOf(),"quelques tranches"),
  DebloatFood("aubergine","Aubergine",FoodCategory.legumes,FoodTier.prefer,229.0,2.0,14.0,"Cuite sans sel : volume satiating et K correct.",listOf("soir-safe"),listOf(),"1 aubergine"),
  DebloatFood("carotte","Carotte",FoodCategory.legumes,FoodTier.prefer,320.0,69.0,12.0,"Base stable, utile en soupe ou râpée sans vinaigrette salée.",listOf("soir-safe"),listOf(),"2 carottes"),
  DebloatFood("brocoli","Brocoli",FoodCategory.legumes,FoodTier.prefer,316.0,33.0,21.0,"K + fibres — portions modérées si digestion sensible.",listOf("soir-safe","high-K"),listOf(),"200 g"),
  DebloatFood("choux-bruxelles","Choux de Bruxelles",FoodCategory.legumes,FoodTier.prefer,389.0,25.0,23.0,"Potassium solide ; vapeur + herbes plutôt que beurre salé.",listOf("high-K"),listOf(),"150 g"),
  DebloatFood("haricots-verts","Haricots verts",FoodCategory.legumes,FoodTier.prefer,211.0,6.0,25.0,"Accompagnement soir-safe, sodium négligeable.",listOf("soir-safe"),listOf(),"200 g"),
  DebloatFood("roquette","Roquette",FoodCategory.legumes,FoodTier.prefer,369.0,27.0,47.0,"Salade high-K ; citron + huile, zéro sel.",listOf("soir-safe","high-K"),listOf(),"1 bol"),
  DebloatFood("mache","Mâche",FoodCategory.legumes,FoodTier.prefer,459.0,4.0,22.0,"Feuille douce très riche en potassium.",listOf("soir-safe","high-K"),listOf(),"1 bol"),
  DebloatFood("betterave","Betterave",FoodCategory.legumes,FoodTier.prefer,325.0,78.0,23.0,"Cuite nature (pas en vinaigrette industrielle).",listOf("high-K"),listOf(),"1 betterave"),
  DebloatFood("champignons","Champignons",FoodCategory.legumes,FoodTier.prefer,318.0,5.0,9.0,"Goût umami sans sel — allié anti-rétention.",listOf("soir-safe","high-K"),listOf(),"150 g"),
  DebloatFood("pasteque","Pastèque",FoodCategory.fruits,FoodTier.hero,112.0,1.0,10.0,"Eau + K : effet drainant rapide sur le visage.",listOf("soir-safe","high-K","tiktok-trend"),listOf(),"2 parts"),
  DebloatFood("melon","Melon",FoodCategory.fruits,FoodTier.hero,267.0,16.0,12.0,"Fruit drainant dense en potassium.",listOf("soir-safe","high-K"),listOf(),"1/2 melon"),
  DebloatFood("ananas","Ananas",FoodCategory.fruits,FoodTier.hero,109.0,1.0,12.0,"Bromélaïne + drainage — frais ou jus 100 % modéré.",listOf("soir-safe","tiktok-trend","high-K"),listOf(),"2 parts"),
  DebloatFood("citron","Citron",FoodCategory.fruits,FoodTier.prefer,138.0,2.0,8.0,"Remplace le sel : acidité + rituels eau citronnée.",listOf("soir-safe"),listOf(),"1/2 citron"),
  DebloatFood("orange","Orange",FoodCategory.fruits,FoodTier.prefer,181.0,0.0,10.0,"Hydratation et K sans sodium.",listOf("soir-safe"),listOf(),"1 orange"),
  DebloatFood("pamplemousse","Pamplemousse",FoodCategory.fruits,FoodTier.prefer,135.0,0.0,9.0,"Léger, drainant, utile le matin.",listOf("soir-safe"),listOf(),"1/2 fruit"),
  DebloatFood("citron-vert","Citron vert",FoodCategory.fruits,FoodTier.prefer,102.0,2.0,6.0,"Assaisonnement anti-sel pour bols et poissons.",listOf("soir-safe"),listOf(),"1/2 fruit"),
  DebloatFood("kiwi","Kiwi",FoodCategory.fruits,FoodTier.prefer,312.0,3.0,17.0,"Potassium élevé dans un petit volume.",listOf("soir-safe","high-K"),listOf(),"2 kiwis"),
  DebloatFood("fraises","Fraises",FoodCategory.fruits,FoodTier.prefer,153.0,1.0,13.0,"Fruit eau + K, collation visage-friendly.",listOf("soir-safe"),listOf(),"150 g"),
  DebloatFood("framboises","Framboises",FoodCategory.fruits,FoodTier.prefer,151.0,1.0,22.0,"Fibres + K, peu de sodium.",listOf("soir-safe"),listOf(),"125 g"),
  DebloatFood("myrtilles","Myrtilles",FoodCategory.fruits,FoodTier.prefer,77.0,1.0,6.0,"Antioxydants utiles, sodium négligeable.",listOf("soir-safe"),listOf(),"125 g"),
  DebloatFood("mures","Mûres",FoodCategory.fruits,FoodTier.prefer,162.0,1.0,20.0,"Baies drainantes, snack simple.",listOf("soir-safe"),listOf(),"125 g"),
  DebloatFood("banane","Banane",FoodCategory.fruits,FoodTier.hero,358.0,1.0,27.0,"Source K star — idéale post-sport / matin.",listOf("high-K"),listOf(),"1 banane"),
  DebloatFood("avocat","Avocat",FoodCategory.fruits,FoodTier.hero,485.0,7.0,29.0,"K très élevé, remplace les sauces salées.",listOf("high-K","soir-safe"),listOf(),"1/2 avocat"),
  DebloatFood("pomme","Pomme",FoodCategory.fruits,FoodTier.prefer,107.0,1.0,5.0,"Base neutre, utile en collation sans sel.",listOf("soir-safe"),listOf(),"1 pomme"),
  DebloatFood("figue","Figue",FoodCategory.fruits,FoodTier.prefer,232.0,1.0,17.0,"Fraîche ou sèche non sucrée : boost K.",listOf("high-K"),listOf(),"2–3 figues"),
  DebloatFood("abricot","Abricot",FoodCategory.fruits,FoodTier.prefer,259.0,1.0,10.0,"Frais ou sec non sucré — potassium concentré.",listOf("high-K"),listOf("abricots-secs"),"3 abricots"),
  DebloatFood("abricots-secs","Abricots secs",FoodCategory.potassium,FoodTier.hero,1162.0,10.0,32.0,"Concentrateur K — portion petite, non sucrés.",listOf("high-K"),listOf(),"4–5 pièces"),
  DebloatFood("peche","Pêche / nectarine",FoodCategory.fruits,FoodTier.prefer,190.0,0.0,9.0,"Fruit eau de saison, sodium nul.",listOf("soir-safe"),listOf(),"1–2 fruits"),
  DebloatFood("raisins-secs","Raisins secs",FoodCategory.potassium,FoodTier.prefer,749.0,11.0,32.0,"K dense — éviter les versions salées/enrobées.",listOf("high-K"),listOf(),"une poignée"),
  DebloatFood("dattes","Dattes",FoodCategory.potassium,FoodTier.prefer,656.0,1.0,43.0,"K + Mg ; portion contrôlée, non fourrées.",listOf("high-K"),listOf(),"2 dattes"),
  DebloatFood("patate-douce","Patate douce",FoodCategory.potassium,FoodTier.hero,337.0,55.0,25.0,"Féculent high-K : vapeur/four, peau si possible.",listOf("high-K","soir-safe"),listOf("pain-baguette"),"1 moyenne"),
  DebloatFood("pomme-de-terre","Pomme de terre",FoodCategory.potassium,FoodTier.hero,421.0,6.0,23.0,"Avec peau, vapeur/four : bombe potassium anti-rétention.",listOf("high-K","soir-safe"),listOf("pain-baguette"),"1–2 pommes de terre"),
  DebloatFood("lentilles","Lentilles",FoodCategory.potassium,FoodTier.prefer,369.0,2.0,36.0,"K + protéines ; rincer si conserve.",listOf("high-K"),listOf(),"150 g cuites"),
  DebloatFood("haricots-blancs","Haricots blancs",FoodCategory.potassium,FoodTier.prefer,561.0,2.0,63.0,"Très haut K/Mg — version nature rincée.",listOf("high-K"),listOf(),"150 g cuits"),
  DebloatFood("haricots-rouges","Haricots rouges",FoodCategory.potassium,FoodTier.prefer,403.0,2.0,45.0,"Légumineuse high-K, rincer les conserves.",listOf("high-K"),listOf(),"150 g cuits"),
  DebloatFood("pois-chiches","Pois chiches",FoodCategory.potassium,FoodTier.prefer,291.0,7.0,48.0,"Base bowl sans sel ; houmous maison sans bicarbonate salé.",listOf("high-K"),listOf(),"150 g cuits"),
  DebloatFood("pois-casses","Pois cassés",FoodCategory.potassium,FoodTier.prefer,362.0,2.0,35.0,"Soupe maison non salée = drainage progressif.",listOf("high-K"),listOf(),"150 g cuits"),
  DebloatFood("amandes","Amandes non salées",FoodCategory.magnesium,FoodTier.prefer,733.0,1.0,270.0,"Mg + K — collation anti-rétention (non salées).",listOf("high-K"),listOf("cacahuetes-salees"),"20–25 g"),
  DebloatFood("pistaches","Pistaches non salées",FoodCategory.magnesium,FoodTier.prefer,1025.0,1.0,121.0,"K exceptionnel si non salées.",listOf("high-K"),listOf("cacahuetes-salees"),"20 g"),
  DebloatFood("graines-courge","Graines de courge",FoodCategory.magnesium,FoodTier.hero,809.0,7.0,592.0,"Meilleur levier Mg alimentaire pour l’équilibre hydrique.",listOf("high-K"),listOf(),"20 g"),
  DebloatFood("noix-cajou","Noix de cajou",FoodCategory.magnesium,FoodTier.prefer,660.0,12.0,292.0,"Mg dense — version nature uniquement.",listOf(),listOf("cacahuetes-salees"),"20 g"),
  DebloatFood("noix-bresil","Noix du Brésil",FoodCategory.magnesium,FoodTier.prefer,659.0,3.0,376.0,"Mg + sélénium ; 2–3 noix suffisent.",listOf(),listOf(),"2–3 noix"),
  DebloatFood("chia","Graines de chia",FoodCategory.magnesium,FoodTier.prefer,407.0,16.0,335.0,"Mg + fibres ; pudding nature sans sirop.",listOf(),listOf(),"15 g"),
  DebloatFood("lin","Graines de lin",FoodCategory.magnesium,FoodTier.prefer,813.0,30.0,392.0,"Mg utile ; moudre pour assimilation.",listOf(),listOf(),"1 c. à s."),
  DebloatFood("sesame","Graines de sésame",FoodCategory.magnesium,FoodTier.prefer,468.0,11.0,351.0,"Mg sur salades — non salé.",listOf(),listOf(),"1 c. à s."),
  DebloatFood("tournesol","Graines de tournesol",FoodCategory.magnesium,FoodTier.prefer,645.0,9.0,325.0,"Collation Mg si non salées.",listOf(),listOf(),"20 g"),
  DebloatFood("chocolat-noir","Chocolat noir ≥ 70 %",FoodCategory.magnesium,FoodTier.prefer,559.0,20.0,228.0,"Mg plaisir contrôlé — éviter lait/sucré.",listOf(),listOf("chocolat-lait"),"20 g"),
  DebloatFood("cacao","Cacao non sucré",FoodCategory.magnesium,FoodTier.prefer,1524.0,21.0,499.0,"Mg ultra-dense en poudre nature.",listOf("high-K"),listOf(),"1 c. à s."),
  DebloatFood("flocons-avoine","Flocons d’avoine",FoodCategory.magnesium,FoodTier.prefer,429.0,2.0,177.0,"Petit-déj Mg ; nature, pas sachets aromatisés.",listOf(),listOf("pain-mie"),"40–50 g"),
  DebloatFood("quinoa","Quinoa",FoodCategory.magnesium,FoodTier.prefer,563.0,5.0,197.0,"Alternative pain/riz blanc : K + Mg.",listOf("high-K"),listOf("pain-baguette"),"80 g crus"),
  DebloatFood("sarrasin","Sarrasin",FoodCategory.magnesium,FoodTier.prefer,460.0,1.0,231.0,"Sans gluten, bon Mg, cuisson sans sel.",listOf(),listOf("pain-baguette"),"80 g crus"),
  DebloatFood("noisettes","Noisettes",FoodCategory.magnesium,FoodTier.prefer,680.0,0.0,163.0,"Mg + K, collation non salée.",listOf(),listOf(),"20 g"),
  DebloatFood("poulet","Poulet (sans peau)",FoodCategory.protein,FoodTier.prefer,256.0,74.0,25.0,"Protéine propre — rôti froid > charcuterie.",listOf("soir-safe"),listOf("jambon-blanc","saucisson"),"150–180 g"),
  DebloatFood("dinde","Dinde (sans peau)",FoodCategory.protein,FoodTier.prefer,242.0,49.0,24.0,"Alternative blanche low-Na à la charcuterie.",listOf("soir-safe"),listOf("jambon-blanc"),"150 g"),
  DebloatFood("oeufs","Œufs",FoodCategory.protein,FoodTier.prefer,138.0,142.0,12.0,"Protéine stable ; cuisson sans sel.",listOf("soir-safe"),listOf(),"2 œufs"),
  DebloatFood("saumon","Saumon (frais)",FoodCategory.protein,FoodTier.hero,363.0,59.0,29.0,"K + oméga-3 — frais, jamais fumé pour le visage.",listOf("high-K","soir-safe"),listOf("saumon-fume"),"140 g"),
  DebloatFood("sardines","Sardines (nature)",FoodCategory.protein,FoodTier.prefer,397.0,100.0,39.0,"K solide ; choisir nature à l’eau/huile, égoutter.",listOf("high-K"),listOf("anchois"),"1 boîte nature"),
  DebloatFood("maquereau","Maquereau",FoodCategory.protein,FoodTier.prefer,314.0,90.0,33.0,"Poisson gras utile ; éviter versions fumées.",listOf("soir-safe"),listOf(),"140 g"),
  DebloatFood("thon","Thon (nature)",FoodCategory.protein,FoodTier.prefer,237.0,50.0,30.0,"Nature à l’eau rincé ; skip sauce soja.",listOf("soir-safe"),listOf(),"120 g"),
  DebloatFood("poisson-blanc","Poisson blanc",FoodCategory.protein,FoodTier.prefer,350.0,78.0,28.0,"Cabillaud/lieu : protéine soir-safe low-Na.",listOf("soir-safe","high-K"),listOf(),"160 g"),
  DebloatFood("yaourt-nature","Yaourt nature",FoodCategory.protein,FoodTier.prefer,255.0,70.0,19.0,"K lacté doux — nature, pas aromatisé sucré.",listOf("soir-safe","high-K"),listOf("fromage-affine"),"1 pot"),
  DebloatFood("fromage-blanc","Fromage blanc",FoodCategory.protein,FoodTier.prefer,141.0,40.0,11.0,"Texture satiante, sodium modéré si nature 0%.",listOf("soir-safe"),listOf(),"150 g"),
  DebloatFood("kefir","Kéfir nature",FoodCategory.protein,FoodTier.prefer,164.0,40.0,14.0,"Option fermentée douce — nature uniquement.",listOf("soir-safe"),listOf(),"200 ml"),
  DebloatFood("tofu","Tofu",FoodCategory.protein,FoodTier.prefer,237.0,7.0,58.0,"Protéine végétale ; nature, pas mariné salé.",listOf("soir-safe"),listOf(),"150 g"),
  DebloatFood("tempeh","Tempeh",FoodCategory.protein,FoodTier.prefer,412.0,9.0,81.0,"K/Mg intéressants — cuisson herbes/citron.",listOf("high-K"),listOf(),"120 g"),
  DebloatFood("persil","Persil",FoodCategory.herbs,FoodTier.hero,554.0,56.0,50.0,"Diurétique star — frais en fin de plat.",listOf("drainant","soir-safe","tiktok-trend"),listOf(),"1/2 bouquet"),
  DebloatFood("gingembre","Gingembre",FoodCategory.herbs,FoodTier.prefer,415.0,13.0,43.0,"Anti-rétention + digestion ; infusion ou râpé.",listOf("soir-safe","tiktok-trend"),listOf(),"1 cm frais"),
  DebloatFood("cumin","Cumin",FoodCategory.herbs,FoodTier.prefer,1788.0,168.0,366.0,"Remplace une partie du sel par la chaleur aromatique.",listOf(),listOf(),"1 c. à c."),
  DebloatFood("ail","Ail",FoodCategory.herbs,FoodTier.prefer,401.0,17.0,25.0,"Goût fort sans saler — modérer si digestion fragile.",listOf(),listOf(),"1 gousse"),
  DebloatFood("oignon","Oignon",FoodCategory.herbs,FoodTier.prefer,146.0,4.0,10.0,"Base aromatique ; portions modérées si ballonnements.",listOf(),listOf(),"1/2 oignon"),
  DebloatFood("basilic","Basilic",FoodCategory.herbs,FoodTier.prefer,295.0,4.0,64.0,"Fraîcheur anti-sel sur tomates et poissons.",listOf("soir-safe"),listOf(),"quelques feuilles"),
  DebloatFood("thym","Thym",FoodCategory.herbs,FoodTier.prefer,609.0,55.0,160.0,"Assaisonnement Mg/K — oublié le cube de bouillon.",listOf("soir-safe"),listOf("bouillon-cube"),"1 pincée"),
  DebloatFood("origan","Origan",FoodCategory.herbs,FoodTier.prefer,1260.0,15.0,270.0,"Aromate puissant pour oublier le sel.",listOf(),listOf(),"1 pincée"),
  DebloatFood("menthe","Menthe",FoodCategory.herbs,FoodTier.prefer,458.0,30.0,63.0,"Eau concombre-menthe : rituel drainant.",listOf("soir-safe","tiktok-trend"),listOf(),"quelques feuilles"),
  DebloatFood("herbes-provence","Herbes de Provence",FoodCategory.herbs,FoodTier.prefer,900.0,40.0,200.0,"Mélange anti-sel pour viandes et légumes.",listOf("soir-safe"),listOf(),"1 c. à c."),
  DebloatFood("vinaigre-cidre","Vinaigre de cidre",FoodCategory.herbs,FoodTier.prefer,73.0,5.0,5.0,"Acidité modérée en vinaigrette sans sel.",listOf("soir-safe"),listOf(),"1 c. à s."),
  DebloatFood("eau-plate","Eau plate",FoodCategory.drinks,FoodTier.hero,0.0,2.0,2.0,"Base absolue : 1,5–2,5 L/jour pour drainer.",listOf("soir-safe"),listOf(),"2 L / jour"),
  DebloatFood("hepar","Hépar",FoodCategory.drinks,FoodTier.prefer,0.0,14.0,119.0,"Eau minérale riche Mg, pauvre Na — alliée visage.",listOf("soir-safe","tiktok-trend"),listOf(),"1 bouteille"),
  DebloatFood("contrex","Contrex",FoodCategory.drinks,FoodTier.prefer,0.0,9.0,84.0,"Mg élevé / Na bas — drainage minéral.",listOf("soir-safe"),listOf(),"1 bouteille"),
  DebloatFood("rozana","Rozana",FoodCategory.drinks,FoodTier.prefer,0.0,8.0,160.0,"Profil Mg fort, sodium bas.",listOf("soir-safe"),listOf(),"1 bouteille"),
  DebloatFood("courmayeur","Courmayeur",FoodCategory.drinks,FoodTier.prefer,0.0,1.0,52.0,"Eau très pauvre en sodium.",listOf("soir-safe"),listOf(),"1 bouteille"),
  DebloatFood("the-vert","Thé vert",FoodCategory.drinks,FoodTier.prefer,27.0,1.0,3.0,"Diurétique doux — éviter après 15 h si sommeil fragile.",listOf("drainant"),listOf(),"2 tasses"),
  DebloatFood("tisane-ortie","Tisane d’ortie",FoodCategory.drinks,FoodTier.hero,40.0,2.0,8.0,"Tendance drainante visage — cure courte.",listOf("drainant","tiktok-trend","soir-safe"),listOf(),"2 tasses"),
  DebloatFood("tisane-queues-cerise","Tisane queues de cerise",FoodCategory.drinks,FoodTier.hero,30.0,1.0,5.0,"Classique anti-rétention (effet diurétique).",listOf("drainant","tiktok-trend","soir-safe"),listOf(),"2 tasses"),
  DebloatFood("tisane-pissenlit","Tisane de pissenlit",FoodCategory.drinks,FoodTier.prefer,25.0,1.0,4.0,"Drainage doux, utile en phase visage gonflé.",listOf("drainant","soir-safe"),listOf(),"1–2 tasses"),
  DebloatFood("tisane-prele","Tisane de prêle",FoodCategory.drinks,FoodTier.prefer,20.0,1.0,4.0,"Support drainage — ne pas abuser.",listOf("drainant"),listOf(),"1 tasse"),
  DebloatFood("tisane-bouleau","Tisane de bouleau",FoodCategory.drinks,FoodTier.prefer,22.0,1.0,3.0,"Tradition anti-rétention.",listOf("drainant","soir-safe"),listOf(),"1–2 tasses"),
  DebloatFood("tisane-fenouil","Tisane de fenouil",FoodCategory.drinks,FoodTier.prefer,18.0,1.0,3.0,"Digestion + légèreté après repas.",listOf("soir-safe"),listOf(),"1 tasse"),
  DebloatFood("tisane-hibiscus","Tisane d’hibiscus",FoodCategory.drinks,FoodTier.prefer,20.0,1.0,3.0,"Boisson colorée low-Na, utile froid.",listOf("soir-safe"),listOf(),"1–2 tasses"),
  DebloatFood("tisane-reine-pres","Tisane reine-des-prés",FoodCategory.drinks,FoodTier.prefer,15.0,1.0,2.0,"Option drainage douce.",listOf("drainant"),listOf(),"1 tasse"),
  DebloatFood("tisane-camomille","Camomille",FoodCategory.drinks,FoodTier.prefer,9.0,1.0,1.0,"Soir : calme + rituel sans caféine.",listOf("soir-safe"),listOf(),"1 tasse le soir"),
  DebloatFood("eau-citronnee","Eau citronnée",FoodCategory.drinks,FoodTier.prefer,20.0,1.0,2.0,"Rituel simple : hydration + signal anti-sel.",listOf("soir-safe","tiktok-trend"),listOf(),"1 L"),
  DebloatFood("eau-concombre-menthe","Eau concombre-menthe-gingembre",FoodCategory.drinks,FoodTier.hero,40.0,2.0,4.0,"Infusion froide drainante — tendance + efficace.",listOf("soir-safe","tiktok-trend","drainant"),listOf(),"1 carafe"),
  DebloatFood("jus-ananas","Jus d’ananas 100 %",FoodCategory.drinks,FoodTier.prefer,130.0,2.0,12.0,"Modéré : bromélaïne, sans sucre ajouté.",listOf("tiktok-trend"),listOf(),"150 ml"),
  DebloatFood("eau-coco","Eau de coco nature",FoodCategory.drinks,FoodTier.hero,250.0,105.0,25.0,"K tendance TikTok — nature, pas aromatisée sucrée.",listOf("high-K","tiktok-trend"),listOf(),"250 ml"),
  DebloatFood("pain-complet","Pain complet",FoodCategory.avoidOther,FoodTier.moderate,250.0,450.0,50.0,"Mieux que blanc mais encore salé — portions courtes.",listOf("evening-risk"),listOf("quinoa","patate-douce"),"1 tranche"),
  DebloatFood("fromage-frais","Fromages frais",FoodCategory.avoidOther,FoodTier.moderate,100.0,300.0,10.0,"Vérifier le sel ; préférer nature nature.",listOf(),listOf("yaourt-nature"),"30–40 g"),
  DebloatFood("yaourt-aromatise","Yaourt aromatisé",FoodCategory.avoidOther,FoodTier.moderate,180.0,60.0,15.0,"Sucres + parfois additifs — le nature gagne pour le visage.",listOf(),listOf("yaourt-nature"),"1 pot"),
  DebloatFood("chocolat-lait","Chocolat au lait",FoodCategory.avoidOther,FoodTier.moderate,340.0,80.0,50.0,"Moins de Mg utile que le noir ≥70 %.",listOf(),listOf("chocolat-noir"),"20 g"),
  DebloatFood("fruits-secs-sales","Fruits secs salés",FoodCategory.avoidOther,FoodTier.moderate,600.0,400.0,150.0,"Le sel annule le bénéfice K/Mg.",listOf("evening-risk"),listOf("amandes","pistaches"),"éviter"),
  DebloatFood("algues","Algues (non rincées)",FoodCategory.avoidOther,FoodTier.moderate,200.0,900.0,100.0,"Souvent très Na — rincer longuement ou éviter.",listOf("evening-risk"),listOf("roquette"),"petite portion rincée"),
  DebloatFood("sel-table","Sel de table / fleur de sel",FoodCategory.avoidSodium,FoodTier.avoid,0.0,38700.0,0.0,"Cause n°1 de rétention faciale — remplacer par herbes + citron.",listOf("evening-risk","ultra-processed"),listOf("herbes-provence","citron","cumin"),null),
  DebloatFood("jambon-blanc","Jambon (cru ou blanc)",FoodCategory.avoidSodium,FoodTier.avoid,280.0,900.0,18.0,"Charcuterie = sodium massif → visage gonflé.",listOf("evening-risk","ultra-processed"),listOf("poulet","dinde"),null),
  DebloatFood("saucisson","Saucisson / salami",FoodCategory.avoidSodium,FoodTier.avoid,300.0,1800.0,20.0,"Bombes de sel — à exclure en phase visage.",listOf("evening-risk","ultra-processed"),listOf("poulet"),null),
  DebloatFood("lardons","Lardons / bacon",FoodCategory.avoidSodium,FoodTier.avoid,250.0,1500.0,15.0,"Sodium + transformation = rétention.",listOf("evening-risk","ultra-processed"),listOf("champignons"),null),
  DebloatFood("pate-rillettes","Pâté / rillettes",FoodCategory.avoidSodium,FoodTier.avoid,150.0,800.0,12.0,"Charcuterie salée — swap protéine fraîche.",listOf("evening-risk","ultra-processed"),listOf("poulet"),null),
  DebloatFood("chorizo","Chorizo",FoodCategory.avoidSodium,FoodTier.avoid,280.0,1600.0,18.0,"Très salé + épicé transformé.",listOf("evening-risk","ultra-processed"),listOf("poulet"),null),
  DebloatFood("fromage-affine","Fromages affinés / salés",FoodCategory.avoidSodium,FoodTier.avoid,100.0,1200.0,25.0,"Roquefort, feta, parmesan, bleu… sodium dominant.",listOf("evening-risk"),listOf("yaourt-nature","fromage-blanc"),null),
  DebloatFood("pain-baguette","Pain (baguette / mie / biscottes)",FoodCategory.avoidSodium,FoodTier.avoid,110.0,650.0,25.0,"1er contributeur de sel en France — swap féculent K.",listOf("evening-risk","ultra-processed"),listOf("patate-douce","pomme-de-terre","quinoa"),null),
  DebloatFood("pain-mie","Pain de mie / biscottes",FoodCategory.avoidSodium,FoodTier.avoid,120.0,500.0,20.0,"Sel caché + ultra-transformé.",listOf("evening-risk","ultra-processed"),listOf("flocons-avoine","quinoa"),null),
  DebloatFood("saumon-fume","Saumon fumé",FoodCategory.avoidSodium,FoodTier.avoid,350.0,1200.0,25.0,"Fumé = sodium élevé ; choisir saumon frais.",listOf("evening-risk"),listOf("saumon"),null),
  DebloatFood("anchois","Anchois / poissons salés",FoodCategory.avoidSodium,FoodTier.avoid,200.0,3600.0,40.0,"Salaison extrême — rétention assurée.",listOf("evening-risk"),listOf("sardines","poisson-blanc"),null),
  DebloatFood("olives-saumure","Olives / cornichons / câpres",FoodCategory.avoidSodium,FoodTier.avoid,80.0,1550.0,10.0,"Saumure = piège sodium sur la table.",listOf("evening-risk"),listOf("concombre","tomate"),null),
  DebloatFood("chips","Chips / apéritifs salés",FoodCategory.avoidSodium,FoodTier.avoid,1200.0,500.0,40.0,"Sel + ultra-transformé : double peine visage.",listOf("evening-risk","ultra-processed"),listOf("concombre","amandes"),null),
  DebloatFood("cacahuetes-salees","Cacahuètes salées",FoodCategory.avoidSodium,FoodTier.avoid,600.0,400.0,160.0,"Le sel annule le Mg — version nature seulement.",listOf("evening-risk"),listOf("amandes","graines-courge"),null),
  DebloatFood("plats-prepares","Plats préparés / traiteur",FoodCategory.avoidSodium,FoodTier.avoid,200.0,900.0,20.0,"Pizza, lasagnes, quiches… sodium industriel.",listOf("evening-risk","ultra-processed"),listOf("poulet","courgette"),null),
  DebloatFood("sauce-soja","Sauce soja / ketchup / mayo / moutarde",FoodCategory.avoidSodium,FoodTier.avoid,180.0,5500.0,30.0,"Sauces = sel concentré. Citron + herbes.",listOf("evening-risk","ultra-processed"),listOf("citron","herbes-provence"),null),
  DebloatFood("bouillon-cube","Bouillons cubes / fonds",FoodCategory.avoidSodium,FoodTier.avoid,50.0,8000.0,5.0,"Sel caché massif dans les soupes.",listOf("evening-risk","ultra-processed"),listOf("thym","ail"),null),
  DebloatFood("conserves-non-rincees","Conserves non rincées",FoodCategory.avoidSodium,FoodTier.avoid,200.0,400.0,20.0,"Rincer = geste visage immédiat.",listOf("evening-risk"),listOf("haricots-blancs"),null),
  DebloatFood("viennoiseries","Viennoiseries / biscuits industriels",FoodCategory.avoidSodium,FoodTier.avoid,100.0,400.0,15.0,"Sel + sucre + UT → rétention et inflammation.",listOf("evening-risk","ultra-processed"),listOf("banane","yaourt-nature"),null),
  DebloatFood("alcool","Alcool (surtout le soir)",FoodCategory.avoidOther,FoodTier.avoid,0.0,5.0,5.0,"Vasodilatation + rétention — visage gonflé au réveil.",listOf("evening-risk"),listOf("eau-plate","tisane-camomille"),null),
  DebloatFood("cafeine-tardive","Café / thé noir après 15 h",FoodCategory.avoidOther,FoodTier.avoid,50.0,5.0,5.0,"La caféine tardive peut perturber le sommeil ; observe ta sensibilité personnelle.",listOf("evening-risk"),listOf("tisane-camomille","tisane-fenouil"),null),
  DebloatFood("sodas","Sodas / jus industriels",FoodCategory.avoidOther,FoodTier.avoid,10.0,20.0,2.0,"Sucres rapides + inflammation.",listOf("evening-risk","ultra-processed"),listOf("eau-coco","eau-citronnee"),null),
  DebloatFood("beurre-sale","Beurre salé / margarine salée",FoodCategory.avoidSodium,FoodTier.avoid,20.0,600.0,2.0,"Sel ajouté inutile — huile + herbes.",listOf("evening-risk"),listOf("avocat"),null),
  DebloatFood("eaux-sodees","Eaux riches en sodium (Badoit, Vichy…)",FoodCategory.avoidSodium,FoodTier.avoid,0.0,170.0,10.0,"Gazeuses très Na en quantité = rétention.",listOf("evening-risk"),listOf("hepar","contrex","eau-plate"),null),
  DebloatFood("fast-food","Fast-food / livraisons salées",FoodCategory.avoidSodium,FoodTier.avoid,300.0,1200.0,30.0,"Combo sel + UT : ennemi direct du visage net.",listOf("evening-risk","ultra-processed"),listOf("poulet","roquette"),null),
 )
 private val byId=all.associateBy { it.id }
 fun item(id:String):DebloatFood?=byId[id]
 fun tier(tier:FoodTier)=all.filter { it.tier==tier }.sortedByDescending { it.score }
 fun search(query:String)=all.filter { FoodNames.normalize(it.name).contains(FoodNames.normalize(query)) }
}
