package com.process.android

// Generated from ProcessLocalizedDebloatFoodContent.swift.
object FoodCopy {
 private val namesFRToEN = mapOf(
  "concombre" to "Cucumber",
  "courgette" to "Zucchini",
  "asperge" to "Asparagus",
  "celeri" to "Celery stalks",
  "fenouil" to "Fennel",
  "artichaut" to "Artichoke",
  "poireau" to "Leek",
  "epinards" to "Spinach",
  "blettes" to "Swiss chard",
  "tomate" to "Tomato",
  "tomate-concentree" to "Unsalted tomato paste",
  "poivron" to "Bell pepper",
  "radis-noir" to "Black radish",
  "aubergine" to "Eggplant",
  "carotte" to "Carrot",
  "brocoli" to "Broccoli",
  "choux-bruxelles" to "Brussels sprouts",
  "haricots-verts" to "Green beans",
  "roquette" to "Arugula",
  "mache" to "Lamb's lettuce",
  "betterave" to "Beet",
  "champignons" to "Mushrooms",
  "pasteque" to "Watermelon",
  "melon" to "Melon",
  "ananas" to "Pineapple",
  "citron" to "Lemon",
  "orange" to "Orange",
  "pamplemousse" to "Grapefruit",
  "citron-vert" to "Lime",
  "kiwi" to "Kiwi",
  "fraises" to "Strawberries",
  "framboises" to "Raspberries",
  "myrtilles" to "Blueberries",
  "mures" to "Blackberries",
  "banane" to "Banana",
  "avocat" to "Avocado",
  "pomme" to "Apple",
  "figue" to "Fig",
  "abricot" to "Apricot",
  "abricots-secs" to "Dried apricots",
  "peche" to "Peach / nectarine",
  "raisins-secs" to "Raisins",
  "dattes" to "Dates",
  "patate-douce" to "Sweet potato",
  "pomme-de-terre" to "Potato",
  "lentilles" to "Lentils",
  "haricots-blancs" to "White beans",
  "haricots-rouges" to "Kidney beans",
  "pois-chiches" to "Chickpeas",
  "pois-casses" to "Split peas",
  "amandes" to "Unsalted almonds",
  "pistaches" to "Unsalted pistachios",
  "graines-courge" to "Pumpkin seeds",
  "noix-cajou" to "Cashews",
  "noix-bresil" to "Brazil nuts",
  "chia" to "Chia seeds",
  "lin" to "Flax seeds",
  "sesame" to "Sesame seeds",
  "tournesol" to "Sunflower seeds",
  "chocolat-noir" to "Dark chocolate ≥ 70%",
  "cacao" to "Unsweetened cocoa",
  "flocons-avoine" to "Oats",
  "quinoa" to "Quinoa",
  "sarrasin" to "Buckwheat",
  "noisettes" to "Hazelnuts",
  "poulet" to "Chicken (skinless)",
  "dinde" to "Turkey (skinless)",
  "oeufs" to "Eggs",
  "saumon" to "Salmon (fresh)",
  "sardines" to "Sardines (plain)",
  "maquereau" to "Mackerel",
  "thon" to "Tuna (plain)",
  "poisson-blanc" to "White fish",
  "yaourt-nature" to "Plain yogurt",
  "fromage-blanc" to "Fromage blanc",
  "kefir" to "Plain kefir",
  "tofu" to "Tofu",
  "tempeh" to "Tempeh",
  "persil" to "Parsley",
  "gingembre" to "Ginger",
  "cumin" to "Cumin",
  "ail" to "Garlic",
  "oignon" to "Onion",
  "basilic" to "Basil",
  "thym" to "Thyme",
  "origan" to "Oregano",
  "menthe" to "Mint",
  "herbes-provence" to "Herbes de Provence",
  "vinaigre-cidre" to "Apple cider vinegar",
  "eau-plate" to "Still water",
  "hepar" to "Hépar",
  "contrex" to "Contrex",
  "rozana" to "Rozana",
  "courmayeur" to "Courmayeur",
  "the-vert" to "Green tea",
  "tisane-ortie" to "Nettle tea",
  "tisane-queues-cerise" to "Cherry stem tea",
  "tisane-pissenlit" to "Dandelion tea",
  "tisane-prele" to "Horsetail tea",
  "tisane-bouleau" to "Birch tea",
  "tisane-fenouil" to "Fennel tea",
  "tisane-hibiscus" to "Hibiscus tea",
  "tisane-reine-pres" to "Meadowsweet tea",
  "tisane-camomille" to "Chamomile",
  "eau-citronnee" to "Lemon water",
  "eau-concombre-menthe" to "Cucumber-mint-ginger water",
  "jus-ananas" to "100% pineapple juice",
  "eau-coco" to "Plain coconut water",
  "pain-complet" to "Whole-grain bread",
  "fromage-frais" to "Fresh cheeses",
  "yaourt-aromatise" to "Flavored yogurt",
  "chocolat-lait" to "Milk chocolate",
  "fruits-secs-sales" to "Salted dried fruit / nuts",
  "algues" to "Seaweed (unrinsed)",
  "sel-table" to "Table salt / fleur de sel",
  "jambon-blanc" to "Ham (cured or cooked)",
  "saucisson" to "Salami / dry sausage",
  "lardons" to "Bacon / lardons",
  "pate-rillettes" to "Pâté / rillettes",
  "chorizo" to "Chorizo",
  "fromage-affine" to "Aged / salty cheeses",
  "pain-baguette" to "Bread (baguette / sandwich / crispbread)",
  "pain-mie" to "Sandwich bread / crispbread",
  "saumon-fume" to "Smoked salmon",
  "anchois" to "Anchovies / salted fish",
  "olives-saumure" to "Olives / pickles / capers",
  "chips" to "Chips / salty snacks",
  "cacahuetes-salees" to "Salted peanuts",
  "plats-prepares" to "Prepared / takeout meals",
  "sauce-soja" to "Soy sauce / ketchup / mayo / mustard",
  "bouillon-cube" to "Bouillon cubes / stock bases",
  "conserves-non-rincees" to "Unrinsed canned foods",
  "viennoiseries" to "Pastries / industrial cookies",
  "alcool" to "Alcohol (especially at night)",
  "cafeine-tardive" to "Coffee / black tea after 3 p.m.",
  "sodas" to "Sodas / industrial juices",
  "beurre-sale" to "Salted butter / salted margarine",
  "eaux-sodees" to "High-sodium waters (Badoit, Vichy…)",
  "fast-food" to "Fast food / salty delivery",
 )
 private val whyFRToEN = mapOf(
  "concombre" to "No. 1 anti-bloat: water + K, almost zero sodium.",
  "courgette" to "Draining vegetable — perfect at night for a cleaner face.",
  "asperge" to "Natural diuretic — helps flush excess water.",
  "celeri" to "Crunchy and draining — keep sodium low by eating it plain.",
  "fenouil" to "High in K, easy to digest, great for limiting retention.",
  "artichaut" to "Supports drainage and adds useful magnesium.",
  "poireau" to "Anti-retention soup base — low sodium if unsalted.",
  "epinards" to "Triple lever: potassium + magnesium + draining volume.",
  "blettes" to "Leaves rich in K/Mg — rinse and cook without salt.",
  "tomate" to "Fresh or plain concentrated: K boost with no added salt.",
  "tomate-concentree" to "Potassium concentrator — choose no-salt-added.",
  "poivron" to "Color, crunch, almost zero sodium.",
  "radis-noir" to "Classic draining food — useful in a short face reset.",
  "aubergine" to "Cooked without salt: filling volume and solid K.",
  "carotte" to "Stable base — soup or grated without salty dressing.",
  "brocoli" to "K + fiber — moderate portions if digestion is sensitive.",
  "choux-bruxelles" to "Solid potassium; steam + herbs instead of salted butter.",
  "haricots-verts" to "Evening-safe side — negligible sodium.",
  "roquette" to "High-K salad; lemon + oil, zero salt.",
  "mache" to "Mild leaf, very high in potassium.",
  "betterave" to "Cook plain (not in industrial vinaigrette).",
  "champignons" to "Umami without salt — anti-retention ally.",
  "pasteque" to "Water + K: fast draining effect on the face.",
  "melon" to "Draining fruit dense in potassium.",
  "ananas" to "Bromelain + drainage — fresh or moderate 100% juice.",
  "citron" to "Replaces salt: acidity + lemon-water rituals.",
  "orange" to "Hydration and K with no sodium.",
  "pamplemousse" to "Light, draining, useful in the morning.",
  "citron-vert" to "Anti-salt seasoning for bowls and fish.",
  "kiwi" to "High potassium in a small volume.",
  "fraises" to "Water + K fruit — face-friendly snack.",
  "framboises" to "Fiber + K, little sodium.",
  "myrtilles" to "Helpful antioxidants, negligible sodium.",
  "mures" to "Draining berries — simple snack.",
  "banane" to "Star K source — ideal post-workout / morning.",
  "avocat" to "Very high K — replaces salty sauces.",
  "pomme" to "Neutral base — useful unsalted snack.",
  "figue" to "Fresh or unsweetened dried: K boost.",
  "abricot" to "Fresh or unsweetened dried — concentrated potassium.",
  "abricots-secs" to "K concentrator — small portion, unsweetened.",
  "peche" to "Seasonal water fruit, zero sodium.",
  "raisins-secs" to "Dense K — avoid salted/coated versions.",
  "dattes" to "K + Mg; controlled portion, not stuffed.",
  "patate-douce" to "High-K starch: steam/oven, skin on if possible.",
  "pomme-de-terre" to "With skin, steam/oven: potassium bomb vs retention.",
  "lentilles" to "K + protein; rinse if canned.",
  "haricots-blancs" to "Very high K/Mg — plain rinsed version.",
  "haricots-rouges" to "High-K legume — rinse canned.",
  "pois-chiches" to "Unsalted bowl base; homemade hummus without salty baking soda.",
  "pois-casses" to "Homemade unsalted soup = gradual drainage.",
  "amandes" to "Mg + K — anti-retention snack (unsalted).",
  "pistaches" to "Exceptional K if unsalted.",
  "graines-courge" to "Best food Mg lever for fluid balance.",
  "noix-cajou" to "Dense Mg — plain version only.",
  "noix-bresil" to "Mg + selenium; 2–3 nuts are enough.",
  "chia" to "Mg + fiber; plain pudding, no syrup.",
  "lin" to "Useful Mg; grind for absorption.",
  "sesame" to "Mg on salads — unsalted.",
  "tournesol" to "Mg snack if unsalted.",
  "chocolat-noir" to "Controlled Mg treat — avoid milk/sweet versions.",
  "cacao" to "Ultra-dense Mg in plain powder.",
  "flocons-avoine" to "Mg breakfast; plain, not flavored packets.",
  "quinoa" to "Bread/white-rice alternative: K + Mg.",
  "sarrasin" to "Gluten-free, good Mg, cook without salt.",
  "noisettes" to "Mg + K, unsalted snack.",
  "poulet" to "Clean protein — cold roast > deli meats.",
  "dinde" to "Low-Na white alternative to deli meats.",
  "oeufs" to "Stable protein; cook without salt.",
  "saumon" to "K + omega-3 — fresh, never smoked for the face.",
  "sardines" to "Solid K; choose plain in water/oil, drain.",
  "maquereau" to "Useful oily fish; avoid smoked versions.",
  "thon" to "Plain in water, rinsed; skip soy sauce.",
  "poisson-blanc" to "Cod/pollock: evening-safe low-Na protein.",
  "yaourt-nature" to "Gentle dairy K — plain, not sweet flavored.",
  "fromage-blanc" to "Filling texture, moderate sodium if plain 0%.",
  "kefir" to "Gentle fermented option — plain only.",
  "tofu" to "Plant protein; plain, not salty marinated.",
  "tempeh" to "Interesting K/Mg — cook with herbs/lemon.",
  "persil" to "Star diuretic — fresh at the end of the dish.",
  "gingembre" to "Anti-retention + digestion; infusion or grated.",
  "cumin" to "Replace some salt with aromatic heat.",
  "ail" to "Strong flavor without salting — ease up if digestion is fragile.",
  "oignon" to "Aromatic base; moderate portions if bloating.",
  "basilic" to "Anti-salt freshness on tomatoes and fish.",
  "thym" to "Mg/K seasoning — forget the bouillon cube.",
  "origan" to "Powerful aromatic to forget salt.",
  "menthe" to "Cucumber-mint water: draining ritual.",
  "herbes-provence" to "Anti-salt blend for meats and vegetables.",
  "vinaigre-cidre" to "Moderate acidity in salt-free vinaigrette.",
  "eau-plate" to "Absolute base: 1.5–2.5 L/day to drain.",
  "hepar" to "Mg-rich mineral water, low Na — face ally.",
  "contrex" to "High Mg / low Na — mineral drainage.",
  "rozana" to "Strong Mg profile, low sodium.",
  "courmayeur" to "Very low-sodium water.",
  "the-vert" to "Gentle diuretic — avoid after 3 p.m. if sleep is fragile.",
  "tisane-ortie" to "Draining face trend — short course.",
  "tisane-queues-cerise" to "Classic anti-retention (diuretic effect).",
  "tisane-pissenlit" to "Gentle drainage — useful when the face is puffy.",
  "tisane-prele" to "Drainage support — don't overdo it.",
  "tisane-bouleau" to "Anti-retention tradition.",
  "tisane-fenouil" to "Digestion + lightness after meals.",
  "tisane-hibiscus" to "Colorful low-Na drink, useful cold.",
  "tisane-reine-pres" to "Gentle drainage option.",
  "tisane-camomille" to "Evening: calm + caffeine-free ritual.",
  "eau-citronnee" to "Simple ritual: hydration + anti-salt signal.",
  "eau-concombre-menthe" to "Cold draining infusion — trendy and effective.",
  "jus-ananas" to "Moderate: bromelain, no added sugar.",
  "eau-coco" to "TikTok-trending K — plain, not sweet flavored.",
  "pain-complet" to "Better than white but still salty — keep portions short.",
  "fromage-frais" to "Check the salt; prefer plain versions.",
  "yaourt-aromatise" to "Sugars + sometimes additives — plain wins for the face.",
  "chocolat-lait" to "Less useful Mg than dark ≥70%.",
  "fruits-secs-sales" to "Salt cancels the K/Mg benefit.",
  "algues" to "Often very high Na — rinse thoroughly or avoid.",
  "sel-table" to "No. 1 cause of facial retention — replace with herbs + lemon.",
  "jambon-blanc" to "Deli meat = massive sodium → puffy face.",
  "saucisson" to "Salt bombs — exclude in a face-focused phase.",
  "lardons" to "Sodium + processing = retention.",
  "pate-rillettes" to "Salty deli — swap for fresh protein.",
  "chorizo" to "Very salty + processed spice.",
  "fromage-affine" to "Roquefort, feta, Parmesan, blue… sodium dominates.",
  "pain-baguette" to "Top salt contributor — swap for a high-K starch.",
  "pain-mie" to "Hidden salt + ultra-processed.",
  "saumon-fume" to "Smoked = high sodium; choose fresh salmon.",
  "anchois" to "Extreme salting — retention guaranteed.",
  "olives-saumure" to "Brine = sodium trap on the table.",
  "chips" to "Salt + ultra-processed: double hit for the face.",
  "cacahuetes-salees" to "Salt cancels the Mg — plain version only.",
  "plats-prepares" to "Pizza, lasagna, quiche… industrial sodium.",
  "sauce-soja" to "Sauces = concentrated salt. Lemon + herbs.",
  "bouillon-cube" to "Massive hidden salt in soups.",
  "conserves-non-rincees" to "Rinse = instant face-friendly move.",
  "viennoiseries" to "Salt + sugar + UP → retention and inflammation.",
  "alcool" to "Vasodilation + retention — puffy face on waking.",
  "cafeine-tardive" to "Late caffeine may affect sleep; observe your own sensitivity.",
  "sodas" to "Fast sugars + inflammation.",
  "beurre-sale" to "Useless added salt — oil + herbs.",
  "eaux-sodees" to "Very high-Na sparkling in volume = retention.",
  "fast-food" to "Salt + UP combo: direct enemy of a clean face.",
 )
 private val portionHintsFRToEN = mapOf(
  "1 L" to "1 L",
  "1 artichaut" to "1 artichoke",
  "1 aubergine" to "1 eggplant",
  "1 banane" to "1 banana",
  "1 betterave" to "1 beet",
  "1 bol" to "1 bowl",
  "1 botte" to "1 bunch",
  "1 bouteille" to "1 bottle",
  "1 boîte nature" to "1 plain can",
  "1 bulbe" to "1 bulb",
  "1 c. à c." to "1 tsp",
  "1 c. à s." to "1 tbsp",
  "1 carafe" to "1 pitcher",
  "1 cm frais" to "1 cm fresh",
  "1 gousse" to "1 clove",
  "1 moyenne" to "1 medium",
  "1 orange" to "1 orange",
  "1 pincée" to "1 pinch",
  "1 poireau" to "1 leek",
  "1 poivron" to "1 bell pepper",
  "1 pomme" to "1 apple",
  "1 pot" to "1 cup",
  "1 tasse" to "1 cup",
  "1 tasse le soir" to "1 cup at night",
  "1 tranche" to "1 slice",
  "1/2 avocat" to "1/2 avocado",
  "1/2 bouquet" to "1/2 bunch",
  "1/2 citron" to "1/2 lemon",
  "1/2 fruit" to "1/2 fruit",
  "1/2 melon" to "1/2 melon",
  "1/2 oignon" to "1/2 onion",
  "1/2 à 1 concombre" to "1/2 to 1 cucumber",
  "120 g" to "120 g",
  "125 g" to "125 g",
  "140 g" to "140 g",
  "15 g" to "15 g",
  "150 g" to "150 g",
  "150 g cuites" to "150 g cooked",
  "150 g cuits" to "150 g cooked",
  "150 ml" to "150 ml",
  "150–180 g" to "150–180 g",
  "160 g" to "160 g",
  "1–2 fruits" to "1–2 fruits",
  "1–2 pommes de terre" to "1–2 potatoes",
  "1–2 tasses" to "1–2 cups",
  "2 L / jour" to "2 L / day",
  "2 c. à s." to "2 tbsp",
  "2 carottes" to "2 carrots",
  "2 dattes" to "2 dates",
  "2 kiwis" to "2 kiwis",
  "2 parts" to "2 servings",
  "2 tasses" to "2 cups",
  "2 tomates" to "2 tomatoes",
  "2 œufs" to "2 eggs",
  "20 g" to "20 g",
  "200 g" to "200 g",
  "200 g cuite" to "200 g cooked",
  "200 ml" to "200 ml",
  "20–25 g" to "20–25 g",
  "250 ml" to "250 ml",
  "2–3 branches" to "2–3 stalks",
  "2–3 figues" to "2–3 figs",
  "2–3 noix" to "2–3 nuts",
  "3 abricots" to "3 apricots",
  "30–40 g" to "30–40 g",
  "40–50 g" to "40–50 g",
  "4–5 pièces" to "4–5 pieces",
  "80 g crus" to "80 g dry",
  "petite portion rincée" to "small rinsed portion",
  "quelques feuilles" to "a few leaves",
  "quelques tranches" to "a few slices",
  "une poignée" to "a handful",
  "éviter" to "avoid",
 )
 private val groceryQuantityFRToEN = mapOf(
  "1 portion" to "1 portion",
  "2 portions" to "2 portions",
  "3–4 portions" to "3–4 portions",
  "6×1,5 L" to "6×1.5 L",
  "4–6 unités" to "4–6 units",
  "2–3 unités" to "2–3 units",
  "1 botte / pot" to "1 bunch / jar",
  "1 paquet" to "1 pack",
  "à éviter" to "avoid",
 )
 fun name(food:DebloatFood,english:Boolean)=if(english) namesFRToEN[food.id] ?: food.name else food.name
 fun why(food:DebloatFood,english:Boolean)=if(english) whyFRToEN[food.id] ?: food.why else food.why
 fun portion(value:String,english:Boolean)=if(english) portionHintsFRToEN[value] ?: groceryQuantityFRToEN[value] ?: value else value
}
