#!/usr/bin/env python3
"""Split extracted copy into translation chunks and merge translated JSON catalogs."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXTRACTED = ROOT / "scripts" / "_extracted_copy.json"
CHUNKS = ROOT / "scripts" / "copy_chunks"
SHARED = ROOT / "Shared"
I18N_JS = ROOT / "website" / "src" / "i18n" / "catalogs.js"
LANGS = ["ja", "de", "ko", "es", "pt-BR"]
INTERP_RE = re.compile(r"\\\([^)]*\)")


def split_chunks(size: int = 510) -> None:
    data = json.loads(EXTRACTED.read_text(encoding="utf-8"))
    static = data["static"]
    CHUNKS.mkdir(parents=True, exist_ok=True)
    for existing in CHUNKS.glob("chunk_*.json"):
        if not existing.name.endswith(".translated.json"):
            # keep translated
            if "translated" not in existing.name:
                pass
    n = 0
    for i in range(0, len(static), size):
        n += 1
        chunk = static[i : i + size]
        (CHUNKS / f"chunk_{n:02d}.json").write_text(
            json.dumps(chunk, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
    interp = data.get("interpolated") or []
    (CHUNKS / "interpolated.json").write_text(
        json.dumps(interp, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"wrote {n} static chunks + interpolated.json ({len(interp)} templates)")


def to_regex(en_raw: str) -> str:
    pieces = INTERP_RE.split(en_raw)
    escaped = [re.escape(p) for p in pieces]
    return "^" + "(.+?)".join(escaped) + "$"


def to_template(translated: str, en_raw: str) -> str:
    """Replace interpolated source tokens in a translated string with $1, $2, ..."""
    parts = INTERP_RE.findall(en_raw)
    out = translated
    for index, token in enumerate(parts, start=1):
        # token is like \(name)
        out = out.replace(token, f"${index}")
        # translators may have dropped backslashes
        bare = token[2:-1]  # name
        out = out.replace(f"\\({bare})", f"${index}")
        out = out.replace(f"$({bare})", f"${index}")
    return out


def merge() -> None:
    exact: dict[str, dict[str, str]] = {lang: {} for lang in LANGS}
    for path in sorted(CHUNKS.glob("chunk_*.translated.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        for en, row in payload.items():
            if not isinstance(row, dict):
                continue
            for lang in LANGS:
                value = row.get(lang)
                if isinstance(value, str) and value.strip():
                    exact[lang][en] = value

    templates: dict[str, list[dict[str, str]]] = {lang: [] for lang in LANGS}
    interp_translated = CHUNKS / "interpolated.translated.json"
    interp_source = CHUNKS / "interpolated.json"
    if interp_translated.exists() and interp_source.exists():
        source_rows = json.loads(interp_source.read_text(encoding="utf-8"))
        trans = json.loads(interp_translated.read_text(encoding="utf-8"))
        by_raw = {row["en_raw"]: row for row in source_rows}
        for en_raw, row in trans.items():
            src = by_raw.get(en_raw)
            if not src:
                continue
            regex = to_regex(src["en_raw"])
            for lang in LANGS:
                value = row.get(lang)
                if isinstance(value, str) and value.strip():
                    templates[lang].append({"re": regex, "to": to_template(value, src["en_raw"])})

    SHARED.mkdir(parents=True, exist_ok=True)
    for lang in LANGS:
        out = {
            "exact": exact[lang],
            "templates": templates[lang],
        }
        (SHARED / f"copy-{lang}.json").write_text(
            json.dumps(out, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        print(f"{lang}: {len(exact[lang])} exact, {len(templates[lang])} templates")

    js_obj = {lang: exact[lang] for lang in LANGS}
    I18N_JS.write_text(
        "/** Auto-generated by scripts/merge_copy_catalogs.py — do not edit by hand. */\n"
        "export const catalogs = "
        + json.dumps(js_obj, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {I18N_JS}")


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1 and sys.argv[1] == "merge":
        merge()
    else:
        split_chunks()
